version: "3"
services:
  gitlab:
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.vcs/'
    image: chifleytech/gitlab-demo
    ports:
    - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: gitlab
        awslogs-region: ${REGION}
        awslogs-stream-prefix: gitlab
