version: '3'

services:
  db:
    image: chifleytech/postgres-demo
    environment:
    - POSTGRES_PASSWORD=password
    logging:
      driver: awslogs
      options:
        awslogs-group: postgres
        awslogs-region: ${REGION}
        awslogs-stream-prefix: postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@localhost
    - PGADMIN_DEFAULT_PASSWORD=password
    logging:
      driver: awslogs
      options:
        awslogs-group: pgadmin
        awslogs-region: ${REGION}
        awslogs-stream-prefix: pgadmin